"""Bash/zsh completion scripts, generated from the argparse tree itself.

The parser `cli.build_parser()` builds is the single source of truth: nothing
here hand-maintains a duplicate list of subcommands or flags. The generated
scripts are plain shell with no external dependencies -- nothing shells out to
Python, or to anything else, at completion time.
"""

from __future__ import annotations

import argparse


# Flags whose argument is a filesystem path: completion falls back to the
# shell's own default file completion instead of a fixed word list.
FILE_PATH_FLAGS: frozenset[str] = frozenset({"--config", "--root", "--findings", "--session"})

PROGRAM = "spec-kit-code-review"


def _subparsers_action(parser: argparse.ArgumentParser) -> argparse._SubParsersAction | None:
    for action in parser._actions:  # noqa: SLF001 - argparse has no public tree walk.
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _long_flags(subparser: argparse.ArgumentParser) -> list[str]:
    flags: list[str] = []
    for action in subparser._actions:  # noqa: SLF001
        for option in action.option_strings:
            if option.startswith("--") and option not in flags:
                flags.append(option)
    return flags


def collect_completion_tree(parser: argparse.ArgumentParser) -> dict[str, list[str]]:
    """``{subcommand: [long flags, sorted]}`` -- what both generators render from."""

    action = _subparsers_action(parser)
    if action is None:
        return {}
    return {name: sorted(_long_flags(subparser)) for name, subparser in action.choices.items()}


_HEADER = f"""\
# {{shell}} completion for {PROGRAM}.
# Generated by `{PROGRAM} completions {{shell}}` -- do not hand-edit; regenerate.
#
# Usage:
#   eval "$({PROGRAM} completions {{shell}})"
"""


def generate_bash_script(tree: dict[str, list[str]]) -> str:
    subcommands = sorted(tree)
    lines: list[str] = [_HEADER.format(shell="bash")]
    lines.append("_spec_kit_code_review() {")
    lines.append("  local cur prev")
    lines.append("  COMPREPLY=()")
    lines.append('  cur="${COMP_WORDS[COMP_CWORD]}"')
    lines.append('  prev="${COMP_WORDS[COMP_CWORD-1]}"')
    lines.append("")
    lines.append('  case "$prev" in')
    lines.append(f"    {'|'.join(sorted(FILE_PATH_FLAGS))})")
    lines.append('      COMPREPLY=($(compgen -f -- "$cur"))')
    lines.append("      return 0")
    lines.append("      ;;")
    lines.append("  esac")
    lines.append("")
    lines.append('  if [ "$COMP_CWORD" -eq 1 ]; then')
    lines.append(f'    COMPREPLY=($(compgen -W "{" ".join(subcommands)}" -- "$cur"))')
    lines.append("    return 0")
    lines.append("  fi")
    lines.append("")
    lines.append('  case "${COMP_WORDS[1]}" in')
    for name in subcommands:
        lines.append(f"    {name})")
        lines.append(f'      COMPREPLY=($(compgen -W "{" ".join(tree[name])}" -- "$cur"))')
        lines.append("      ;;")
    lines.append("  esac")
    lines.append("}")
    lines.append(f"complete -F _spec_kit_code_review {PROGRAM}")
    return "\n".join(lines) + "\n"


def generate_zsh_script(tree: dict[str, list[str]]) -> str:
    subcommands = sorted(tree)
    lines: list[str] = [f"#compdef {PROGRAM}", ""]
    lines.append(_HEADER.format(shell="zsh"))
    lines.append("_spec_kit_code_review() {")
    lines.append("  local -a subcommands")
    lines.append(f"  subcommands=({' '.join(subcommands)})")
    lines.append("")
    lines.append("  if (( CURRENT == 2 )); then")
    lines.append("    compadd -a subcommands")
    lines.append("    return")
    lines.append("  fi")
    lines.append("")
    lines.append('  local prev="${words[CURRENT-1]}"')
    lines.append('  case "$prev" in')
    lines.append(f"    {'|'.join(sorted(FILE_PATH_FLAGS))})")
    lines.append("      _files")
    lines.append("      return")
    lines.append("      ;;")
    lines.append("  esac")
    lines.append("")
    lines.append("  local -a flags")
    lines.append('  case "${words[2]}" in')
    for name in subcommands:
        lines.append(f"    {name})")
        lines.append(f"      flags=({' '.join(tree[name])})")
        lines.append("      ;;")
    lines.append("    *)")
    lines.append("      flags=()")
    lines.append("      ;;")
    lines.append("  esac")
    lines.append("  compadd -a flags")
    lines.append("}")
    lines.append("")
    lines.append(f"compdef _spec_kit_code_review {PROGRAM}")
    return "\n".join(lines) + "\n"


def generate_completion_script(shell: str, parser: argparse.ArgumentParser) -> str:
    tree = collect_completion_tree(parser)
    if shell == "bash":
        return generate_bash_script(tree)
    if shell == "zsh":
        return generate_zsh_script(tree)
    raise ValueError(f"unsupported shell: {shell!r}")
