"""Bash/zsh completion scripts for `spec-kit-linear`, generated by
introspecting the argparse parser tree `cli.build_parser()` builds.

This is the single source of truth: the generators below never hand-maintain
a duplicate list of subcommands or flags. `completions` (the CLI subcommand that calls into this module) is local-only
developer sugar; the package README documents the one-liners to eval/source
its output.

Output is plain POSIX-ish shell text with no external dependencies: nothing
here (and nothing in the generated scripts) shells out to Python, or to
anything else, at completion time.
"""

from __future__ import annotations

import argparse

# Flags whose argument is a filesystem path: completion falls back to the
# shell's own default file completion instead of a fixed word list.
FILE_PATH_FLAGS: frozenset[str] = frozenset({"--config", "--root"})


def _subparsers_action(parser: argparse.ArgumentParser) -> argparse._SubParsersAction | None:
    for action in parser._actions:  # noqa: SLF001 - argparse has no public tree walk.
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _long_flags(subparser: argparse.ArgumentParser) -> list[str]:
    flags: list[str] = []
    for action in subparser._actions:  # noqa: SLF001
        for option in action.option_strings:
            if option.startswith("--") and option not in flags:
                flags.append(option)
    return flags


def collect_completion_tree(parser: argparse.ArgumentParser) -> dict[str, list[str]]:
    """``{subcommand: [long flags, sorted]}`` -- the one structure both shell
    generators render from, and what the completeness test asserts against.
    """

    action = _subparsers_action(parser)
    if action is None:
        return {}
    tree: dict[str, list[str]] = {}
    for name, subparser in action.choices.items():
        tree[name] = sorted(_long_flags(subparser))
    return tree


_HEADER = """\
# {shell} completion for spec-kit-linear.
# Generated by `spec-kit-linear completions {shell}` -- do not hand-edit;
# regenerate instead.
#
# Usage (assumes `spec-kit-linear` resolves on PATH, e.g. via an alias to
# `bash .specify/extensions/linear/scripts/bash/run.sh` in a consumer
# repository):
#   eval "$(spec-kit-linear completions {shell})"
"""


def generate_bash_script(tree: dict[str, list[str]]) -> str:
    subcommands = sorted(tree)
    lines: list[str] = [_HEADER.format(shell="bash")]
    lines.append("_spec_kit_linear() {")
    lines.append('  local cur prev')
    lines.append('  COMPREPLY=()')
    lines.append('  cur="${COMP_WORDS[COMP_CWORD]}"')
    lines.append('  prev="${COMP_WORDS[COMP_CWORD-1]}"')
    lines.append("")
    lines.append("  case \"$prev\" in")
    lines.append(f"    {'|'.join(sorted(FILE_PATH_FLAGS))})")
    lines.append('      COMPREPLY=($(compgen -f -- "$cur"))')
    lines.append("      return 0")
    lines.append("      ;;")
    lines.append("  esac")
    lines.append("")
    lines.append('  if [ "$COMP_CWORD" -eq 1 ]; then')
    lines.append(f'    COMPREPLY=($(compgen -W "{" ".join(subcommands)}" -- "$cur"))')
    lines.append("    return 0")
    lines.append("  fi")
    lines.append("")
    lines.append('  case "${COMP_WORDS[1]}" in')
    for name in subcommands:
        flags = " ".join(tree[name])
        lines.append(f"    {name})")
        lines.append(f'      COMPREPLY=($(compgen -W "{flags}" -- "$cur"))')
        lines.append("      ;;")
    lines.append("  esac")
    lines.append("}")
    lines.append("complete -F _spec_kit_linear spec-kit-linear")
    return "\n".join(lines) + "\n"


def generate_zsh_script(tree: dict[str, list[str]]) -> str:
    subcommands = sorted(tree)
    lines: list[str] = ["#compdef spec-kit-linear", ""]
    lines.append(_HEADER.format(shell="zsh"))
    lines.append("_spec_kit_linear() {")
    lines.append("  local -a subcommands")
    lines.append(f"  subcommands=({' '.join(subcommands)})")
    lines.append("")
    lines.append("  if (( CURRENT == 2 )); then")
    lines.append("    compadd -a subcommands")
    lines.append("    return")
    lines.append("  fi")
    lines.append("")
    lines.append('  local prev="${words[CURRENT-1]}"')
    lines.append("  case \"$prev\" in")
    lines.append(f"    {'|'.join(sorted(FILE_PATH_FLAGS))})")
    lines.append("      _files")
    lines.append("      return")
    lines.append("      ;;")
    lines.append("  esac")
    lines.append("")
    lines.append("  local -a flags")
    lines.append('  case "${words[2]}" in')
    for name in subcommands:
        flags = " ".join(tree[name])
        lines.append(f"    {name})")
        lines.append(f"      flags=({flags})")
        lines.append("      ;;")
    lines.append("    *)")
    lines.append("      flags=()")
    lines.append("      ;;")
    lines.append("  esac")
    lines.append("  compadd -a flags")
    lines.append("}")
    lines.append("")
    lines.append("compdef _spec_kit_linear spec-kit-linear")
    return "\n".join(lines) + "\n"


def generate_completion_script(shell: str, parser: argparse.ArgumentParser) -> str:
    tree = collect_completion_tree(parser)
    if shell == "bash":
        return generate_bash_script(tree)
    if shell == "zsh":
        return generate_zsh_script(tree)
    raise ValueError(f"unsupported shell: {shell!r}")
