"""Goldens of the review's own artifacts: findings, plan, and session.

Doc "Goldens". These three files are what a later stage publishes and what an
operator reads, so a change in them is a change in the review itself and should
be read line by line rather than regenerated by reflex.

Regenerate deliberately::

    SPECKIT_CODE_REVIEW_UPDATE_GOLDEN=1 pytest tests/unit/test_golden_review.py

The known input deliberately includes what the contract asks the golden to
cover: ties on `path`/`start_line`/`severity` that only the full canonical key
can break, a `side: LEFT` finding, a finding outside every hunk, and a finding
that must be discarded because it does not exist in the candidate.
"""

from __future__ import annotations

import json
import os
import re
import unittest
from dataclasses import dataclass
from pathlib import Path

from spec_kit_code_review.anchors import Hunk, HunkMap
from spec_kit_code_review.budget import BudgetReport, FileBudget
from spec_kit_code_review.findings import normalize
from spec_kit_code_review.publish import build_plan
from spec_kit_code_review.verdict import derive
from tests.support.repo import TemporaryRepository
from spec_kit_code_review.git import open_git


GOLDEN = Path(__file__).resolve().parents[1] / "golden"
SUFFIX = "a7f3c1e9"


@dataclass
class Candidate:
    candidate_id: str = "c" * 64
    head_commit: str = "b" * 40
    merge_base: str = "a" * 40
    repository: str | None = "tserdeiro/consumer"
    pr_number: int | None = 128
    author: str = "contributor"


def _entry(**overrides):
    payload = {
        "path": "src/module.py",
        "start_line": 11,
        "end_line": 11,
        "side": "RIGHT",
        "severity": "blocking",
        "category": "correctness",
        "title": "The input is never validated",
        "content": "`added_a` is assigned from unvalidated input.",
        "rule_source": "repo",
    }
    payload.update(overrides)
    return payload


KNOWN_INPUT = [
    # Two findings that tie on path, start_line and severity: only `end_line`,
    # `title` and the content digest can order them.
    _entry(title="B — the second of a tie", content="second"),
    _entry(title="A — the first of a tie", content="first"),
    _entry(end_line=12, title="A — the first of a tie", content="first"),
    # A deleted line: legitimate, never anchored, always reported. This one is
    # about a file the candidate **removed entirely** -- the case that was being
    # discarded as "the path does not exist at the head".
    _entry(
        path="src/removed.py",
        side="LEFT",
        start_line=1,
        end_line=2,
        severity="major",
        category="tests",
        title="A test was deleted with the code it covered",
        content="The guard and its test were removed together.",
        rule_source="sdd",
        sdd_reference="specs/001-thing/spec.md#FR-001",
    ),
    # Outside every hunk: kept, degraded to the summary.
    _entry(
        start_line=2,
        end_line=2,
        severity="minor",
        category="maintainability",
        title="An untouched line is worth revisiting",
        content="Line 2 predates this candidate.",
    ),
    # A hallucination: discarded with a diagnostic, and recorded as discarded.
    _entry(
        path="src/never_existed.py",
        severity="nit",
        category="style",
        title="A file the candidate does not contain",
        content="This finding cites a path that does not exist at the head.",
    ),
]


class GoldenReviewTests(unittest.TestCase):
    def setUp(self) -> None:
        self.repository = TemporaryRepository()
        self.addCleanup(self.repository.cleanup)
        self.repository.write("src/module.py", "".join(f"line_{index}\n" for index in range(10)))
        self.repository.write("src/removed.py", "guard = validate(x)\nassert guard\n")
        self.repository.git("add", "--all")
        self.repository.git("commit", "-m", "base")
        self.base = self.repository.head()
        self.repository.write(
            "src/module.py", "".join(f"line_{index}\n" for index in range(10)) + "added_a = 1\nadded_b = 2\n"
        )
        self.repository.git("rm", "--quiet", "src/removed.py")
        self.repository.git("add", "--all")
        self.repository.git("commit", "-m", "candidate")
        self.head = self.repository.head()
        self.git = open_git(self.repository.path)
        self.hunks = HunkMap(hunks=(Hunk("src/module.py", 11, 12),))

    def _compare(self, name: str, payload: dict) -> None:
        rendered = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
        path = GOLDEN / name
        if os.environ.get("SPECKIT_CODE_REVIEW_UPDATE_GOLDEN"):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered, encoding="utf-8")
        self.assertTrue(path.is_file(), f"missing golden {path}; regenerate with SPECKIT_CODE_REVIEW_UPDATE_GOLDEN=1")
        self.assertEqual(rendered, path.read_text(encoding="utf-8"))

    def _normalized(self):
        return normalize(
            KNOWN_INPUT,
            git=self.git,
            head_commit=self.head,
            merge_base=self.base,
            hunks=self.hunks,
            source_sha256="d" * 64,
        )

    def test_findings_match_their_golden(self) -> None:
        normalized = self._normalized()
        verdict = derive(normalized.findings)

        self._compare("findings.json", {**normalized.as_dict(), "verdict": verdict.as_dict()})

    def test_the_golden_pins_the_full_canonical_order(self) -> None:
        recorded = json.loads((GOLDEN / "findings.json").read_text(encoding="utf-8"))
        findings = recorded["findings"]

        self.assertEqual([item["id"] for item in findings], [f"F{index:03d}" for index in range(1, len(findings) + 1)])
        # Ties on path/start_line/severity resolved by end_line, then title,
        # then the digest of the content -- and nothing left ambiguous.
        keys = [
            (item["path"], item["start_line"], item["end_line"], item["severity"], item["category"], item["title"])
            for item in findings
        ]
        self.assertEqual(keys, sorted(keys))

    def test_the_golden_carries_the_left_side_finding_degraded(self) -> None:
        recorded = json.loads((GOLDEN / "findings.json").read_text(encoding="utf-8"))

        left = [item for item in recorded["findings"] if item["side"] == "LEFT"]
        self.assertEqual(len(left), 1)
        self.assertFalse(left[0]["anchorable"])
        self.assertIn("LEFT", left[0]["degraded_reason"])
        # About a file the candidate deleted: checked against the merge base,
        # which is the frame it is numbered in.
        self.assertEqual(left[0]["path"], "src/removed.py")

    def test_the_golden_shows_a_degraded_finding_keeping_its_explanation(self) -> None:
        recorded = json.loads((GOLDEN / "publication-plan.json").read_text(encoding="utf-8"))

        self.assertIn("The guard and its test were removed together.", recorded["summary_body"])

    def test_the_golden_records_the_discarded_hallucination(self) -> None:
        recorded = json.loads((GOLDEN / "findings.json").read_text(encoding="utf-8"))

        self.assertEqual(len(recorded["discarded"]), 1)
        self.assertEqual(recorded["discarded"][0]["path"], "src/never_existed.py")
        self.assertNotIn("src/never_existed.py", [item["path"] for item in recorded["findings"]])

    def test_the_publication_plan_matches_its_golden(self) -> None:
        normalized = self._normalized()
        verdict = derive(normalized.findings)
        plan = build_plan(
            candidate=Candidate(),
            verdict=verdict,
            findings=normalized.findings,
            packet_sha256="p" * 64,
            suffix=SUFFIX,
            budget=BudgetReport(
                entries=(FileBudget("src/module.py", 2, 2),), limit=400
            ),
            event_ceiling="request-changes",
            request_changes=True,
            authenticated_user="reviewer",
            batch_size=2,
            max_inline_comments=2,
        )

        self._compare("publication-plan.json", plan.as_dict())

    def test_the_plan_golden_shows_both_degradation_paths(self) -> None:
        recorded = json.loads((GOLDEN / "publication-plan.json").read_text(encoding="utf-8"))
        reasons = {item["reason"] for item in recorded["degraded"]}

        self.assertIn("beyond publish.max_inline_comments", reasons)
        self.assertTrue(any("LEFT" in reason for reason in reasons))
        self.assertTrue(any("not inside a hunk" in reason for reason in reasons))
        self.assertFalse(recorded["executed"])
        self.assertEqual(recorded["event"], "REQUEST_CHANGES")

    def test_the_plan_golden_never_carries_an_approval(self) -> None:
        recorded = json.loads((GOLDEN / "publication-plan.json").read_text(encoding="utf-8"))

        self.assertNotEqual(recorded["event"], "APPROVE")
        self.assertIn("not an approval", recorded["summary_body"])

    def test_the_plan_golden_records_the_range_it_was_built_from(self) -> None:
        recorded = json.loads((GOLDEN / "publication-plan.json").read_text(encoding="utf-8"))

        self.assertEqual(recorded["head_commit"], "b" * 40)
        self.assertEqual(recorded["merge_base"], "a" * 40)


class GoldenSessionTests(unittest.TestCase):
    """The phase-1 session, with its digests and the state it will restore."""

    def test_the_session_matches_its_golden(self) -> None:
        from tests.unit.test_cli import RunCommandCase

        case = RunCommandCase("run")
        case.setUp()
        try:
            code, payload = case._phase_one()
            self.assertEqual(code, 0)
            recorded = json.loads((Path(payload["session"]["path"]) / "session.json").read_text(encoding="utf-8"))
            workspace = str(case.workspace)
        finally:
            case.doCleanups()

        # Everything that legitimately varies per run is replaced by a token, so
        # what the golden pins is the *shape*: which keys exist, which digests
        # are recorded, and what the restore state looks like.
        skeleton = _skeleton(recorded)
        path = GOLDEN / "session.json"
        rendered = json.dumps(skeleton, indent=2, sort_keys=True) + "\n"
        # Absolute paths of the run itself -- the temporary consumer, the fake
        # engine, the evidence root -- are per-run by nature. The golden pins
        # the shape around them, not the machine they happened on.
        for prefix in {workspace, str(Path(workspace).resolve())}:
            rendered = rendered.replace(prefix, "<workspace>")
        # Commit ids and the repository slug derived from the temporary path are
        # per-run for the same reason; the golden pins that they are *there*.
        rendered = re.sub(r"\b[0-9a-f]{40}\b", "<sha1>", rendered)
        rendered = re.sub(r"path-[0-9a-f]{16}", "path-<slug>", rendered)
        if os.environ.get("SPECKIT_CODE_REVIEW_UPDATE_GOLDEN"):
            path.write_text(rendered, encoding="utf-8")
        self.assertEqual(rendered, path.read_text(encoding="utf-8"))

    def test_the_session_golden_records_what_withdraws_the_environment(self) -> None:
        recorded = json.loads((GOLDEN / "session.json").read_text(encoding="utf-8"))

        self.assertEqual(recorded["phase"], "open")
        self.assertIn("worktree_path", recorded["environment"])
        self.assertIn("permitted_git_writes", recorded["environment"])
        for key in ("packet_sha256", "pr_metadata_sha256", "containment_suffix", "config_sha256"):
            with self.subTest(key=key):
                self.assertIn(key, recorded)


_VARIABLE_KEYS = {
    "head_commit",
    "merge_base",
    "candidate_id",
    "base_commit",
    "resolved_at",
    "base_observed_at",
    "opened_at",
    "closed_at",
    "path",
    "root",
    "sha256",
    "packet_sha256",
    "pr_metadata_sha256",
    "containment_suffix",
    "config_sha256",
    "rules_sha256",
    "executable",
    "config_path",
    "worktree_path",
    "digest",
    "started_at",
    "finished_at",
    "duration_ms",
    "bytes",
    "version",
}


def _skeleton(payload):
    """Replace per-run values with a token, keeping the shape and the keys."""

    if isinstance(payload, dict):
        return {
            key: ("<variable>" if key in _VARIABLE_KEYS and not isinstance(value, (dict, list)) else _skeleton(value))
            for key, value in payload.items()
        }
    if isinstance(payload, list):
        return [_skeleton(item) for item in payload]
    return payload


if __name__ == "__main__":  # pragma: no cover - convenience for local runs
    unittest.main()
