#!/usr/bin/env python3
"""Specify CLI Event Dispatcher — dispatches agent runtime events.

Generated by: specify integration install/upgrade
Do not edit manually.

Self-contained: it prefers `specify_cli` when the package is importable
(durable pip/pipx/uv-tool install) and falls back to an inline stdlib-only
resolver when Spec Kit is not installed at runtime — e.g. a one-time `uvx`
init whose environment is discarded after `specify init` finishes (R1). In
both cases it resolves the event's command template and runs its script
directly, without requiring a persistent `specify` executable on PATH.
"""
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path, PurePosixPath, PureWindowsPath


def _script_under_base(base, token, project_root):
    """Return token resolved under base, or None if it leaves the project."""
    posix_path = PurePosixPath(token)
    win_path = PureWindowsPath(token)
    if posix_path.anchor or win_path.anchor:
        return None
    try:
        root = project_root.resolve()
        candidate = (base / token).resolve()
        candidate.relative_to(root)
    except (OSError, ValueError):
        return None
    return candidate


def _find_command_template(command_name, project_root):
    """Locate the command's .md template. Returns (path, ext_id|None)."""
    exts_dir = project_root / ".specify" / "extensions"
    disabled_ids = set()
    registry_file = exts_dir / ".registry"
    if registry_file.is_file():
        try:
            reg_data = json.loads(registry_file.read_text(encoding="utf-8"))
            for ext_id, meta in reg_data.get("extensions", {}).items():
                if isinstance(meta, dict) and meta.get("enabled") is False:
                    disabled_ids.add(ext_id)
        except Exception:
            pass

    stem = command_name.replace("speckit.", "").replace("spec.", "")

    # 1. Manifest-driven resolution from extension.yml in enabled extensions (Suppressed #1)
    if exts_dir.is_dir():
        for ext_dir in sorted(exts_dir.iterdir()):
            if not ext_dir.is_dir() or ext_dir.name in disabled_ids:
                continue
            ext_yml = ext_dir / "extension.yml"
            if ext_yml.is_file():
                try:
                    yml_text = ext_yml.read_text(encoding="utf-8")
                    cur_name = None
                    cur_file = None
                    in_provides = False
                    in_commands = False
                    for line in yml_text.splitlines():
                        stripped = line.strip()
                        if stripped == "provides:":
                            in_provides = True
                            continue
                        if in_provides and stripped == "commands:":
                            in_commands = True
                            continue
                        if in_commands and stripped and not line[0].isspace():
                            in_provides = False
                            in_commands = False
                            continue
                        if in_commands:
                            if "name:" in line:
                                cur_name = line.split("name:", 1)[1].strip().strip('"').strip("'")
                            if "file:" in line:
                                cur_file = line.split("file:", 1)[1].strip().strip('"').strip("'")
                            if cur_name and cur_file:
                                if cur_name == command_name:
                                    candidate = ext_dir / cur_file
                                    if candidate.exists():
                                        return candidate, ext_dir.name
                                cur_name = None
                                cur_file = None
                except Exception:
                    pass

    # 2. On-disk extension commands by file stem (non-disabled extensions)
    if exts_dir.is_dir():
        for ext_dir in sorted(exts_dir.iterdir()):
            if not ext_dir.is_dir() or ext_dir.name in disabled_ids:
                continue
            cmds_dir = ext_dir / "commands"
            if cmds_dir.is_dir():
                for f in cmds_dir.glob("*.md"):
                    if f.stem == command_name or f.stem == stem:
                        return f, ext_dir.name

    # 3. Core templates in the project
    core = project_root / ".specify" / "templates" / "commands"
    if core.is_dir():
        candidate = core / (stem + ".md")
        if candidate.exists():
            return candidate, None
    return None, None


def _script_variant(project_root):
    """Return the project's persisted script type ('sh'|'ps'|'py')."""
    default = "ps" if os.name == "nt" else "sh"
    init_opts = project_root / ".specify" / "init-options.json"
    try:
        data = json.loads(init_opts.read_text(encoding="utf-8"))
        script = data.get("script")
        if script in ("sh", "ps", "py"):
            return script
    except Exception:
        pass
    return default


def _extract_scripts(template_path):
    """Parse the scripts: block from a command template's frontmatter."""
    try:
        content = template_path.read_text(encoding="utf-8")
    except Exception:
        return {}
    m = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
    if not m:
        return {}
    scripts = {}
    in_scripts = False
    for line in m.group(1).splitlines():
        if line.rstrip() == "scripts:":
            in_scripts = True
            continue
        if in_scripts and line and not line[0].isspace():
            break
        if in_scripts and ":" in line:
            k, _, v = line.partition(":")
            scripts[k.strip()] = v.strip()
    return scripts


def _resolve_argv(template_path, project_root, ext_id):
    """Resolve the command's script to a runnable argv (stdlib only)."""
    scripts = _extract_scripts(template_path)
    if not scripts:
        return None
    requested = _script_variant(project_root)
    order = (requested,) if requested in scripts else ()
    fallbacks = (requested, "ps" if requested != "ps" else "sh", "py", "sh")
    seen = set()
    for cand in order + fallbacks:
        if cand in seen:
            continue
        seen.add(cand)
        if cand in scripts:
            variant = cand
            break
    else:
        return None
    script_cmd = scripts.get(variant, "").strip()
    if not script_cmd:
        return None

    base = (project_root / ".specify" / "extensions" / ext_id) if ext_id else (project_root / ".specify")
    try:
        tokens = shlex.split(script_cmd, posix=(os.name != "nt"))
    except ValueError:
        return None
    if not tokens:
        return None
    script_abs = _script_under_base(base, tokens[0], project_root)
    if script_abs is None or not script_abs.exists():
        return None
    rest = tokens[1:]

    if variant == "py":
        # .py files aren't directly executable; run under the dispatcher's own
        # Python (sys.executable), which is always available here.
        return [sys.executable or "python3", str(script_abs), *rest]
    if variant == "ps":
        launcher = shutil.which("pwsh") or shutil.which("powershell")
        if not launcher:
            return None
        return [launcher, "-File", str(script_abs), *rest]
    # sh: direct on POSIX; a bash/sh launcher on Windows.
    if os.name == "nt":
        launcher = shutil.which("bash") or shutil.which("sh")
        if launcher:
            return [launcher, str(script_abs), *rest]
        return None
    return [str(script_abs), *rest]


def _run_inline(command_name, payload, project_root, timeout, envelope="plain", native_event=""):
    """Resolve and run the event command with stdlib only (no specify_cli)."""
    template_path, ext_id = _find_command_template(command_name, project_root)
    if not template_path:
        return 0  # command not found: fail open (no-op) for lifecycle events
    argv = _resolve_argv(template_path, project_root, ext_id)
    if not argv:
        return 0
    try:
        result = subprocess.run(
            argv,
            input=payload,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=str(project_root),
        )
        if result.stdout:
            _emit(result.stdout, envelope, native_event)
        if result.returncode != 0:
            if result.stderr:
                sys.stderr.write(result.stderr)
            return result.returncode
        return 0
    except subprocess.TimeoutExpired:
        print(f"Event {command_name} timed out", file=sys.stderr)
        return 2
    except Exception as e:
        print(f"Event {command_name} error: {e}", file=sys.stderr)
        return 2


def _emit(output, envelope, native_event=""):
    """Write handler output to stdout in the agent's context-injection shape.

    Not every agent injects a hook's plain-text stdout as model context:
    Gemini/Tabnine/Qwen/Devin are JSON-only protocols (plain text becomes
    user-facing noise, never context), Copilot discards non-JSON stdout, and
    Cursor parses stdout as JSON. The native hook command passes the envelope
    as the dispatcher's 5th argument (see events_context_envelope on the
    integration classes), and the native event name as the 6th argument so
    hookSpecificOutput can include hookEventName:

      hookSpecificOutput → {"hookSpecificOutput": {"hookEventName": ..., "additionalContext": ...}}
      additionalContext  → {"additionalContext": ...}   (top-level, Copilot)
      additional_context → {"additional_context": ...}  (top-level, Cursor)
      hook_specific_output → {"decision": "allow", "hook_specific_output":
                           {"additional_context": ...}} (Vibe: any non-empty
                           stdout must parse as a HookStructuredResponse or
                           the hook is reported failed and output dropped)
      suppress           → emit nothing (strict-JSON agents on events whose
                           output can't be used)
      plain (default)    → passthrough (Claude/Codex inject plain stdout)

    Empty output emits nothing under any envelope (an empty additionalContext
    is useless noise).
    """
    if not output:
        return
    if envelope == "suppress":
        return
    if envelope == "hookSpecificOutput":
        payload = {"additionalContext": output}
        if native_event:
            payload["hookEventName"] = native_event
        sys.stdout.write(json.dumps({"hookSpecificOutput": payload}) + "\n")
        return
    if envelope == "additionalContext":
        sys.stdout.write(json.dumps({"additionalContext": output}) + "\n")
        return
    if envelope == "additional_context":
        sys.stdout.write(json.dumps({"additional_context": output}) + "\n")
        return
    if envelope == "hook_specific_output":
        sys.stdout.write(json.dumps({"decision": "allow", "hook_specific_output": {"additional_context": output}}) + "\n")
        return
    sys.stdout.write(output)


def main():
    if len(sys.argv) < 3:
        sys.exit(0)
    command_name = sys.argv[1]
    # event_name is accepted for argv-compat with the native hook command but
    # is not needed for resolution (the command template drives everything).
    _event_name = sys.argv[2]
    # Optional 4th arg: per-handler timeout in seconds (S4).
    timeout = 120
    if len(sys.argv) >= 4:
        try:
            timeout = int(sys.argv[3])
        except (TypeError, ValueError):
            timeout = 120
    # Optional 5th arg: context-injection envelope for stdout (C13): plain
    # (default), hookSpecificOutput, additionalContext, additional_context,
    # hook_specific_output, or suppress. Unknown values fall back to plain
    # passthrough.
    envelope = sys.argv[4] if len(sys.argv) >= 5 else "plain"
    if envelope not in ("plain", "hookSpecificOutput", "additionalContext", "additional_context", "hook_specific_output", "suppress"):
        envelope = "plain"
    # Optional 6th arg: native event name for hookSpecificOutput's
    # hookEventName field (required by Qwen's hooks spec; included by
    # Gemini/Tabnine/Devin which derive from the same protocol).
    native_event = sys.argv[5] if len(sys.argv) >= 6 else ""
    payload = sys.stdin.read() if not sys.stdin.isatty() else "{}"
    project_root = Path(__file__).parent.parent.resolve()

    # Preferred path: specify_cli is importable (durable install) — delegate to
    # the full resolver, which also handles extension manifests whose file stem
    # differs from the command name and the project's custom script selection.
    # Require EVENT_SCRIPT_PATH_CONFINEMENT so a stale global install cannot
    # bypass the generated dispatcher's path guard.
    try:
        from specify_cli.events import (
            EVENT_SCRIPT_PATH_CONFINEMENT as _confine_ok,
            resolve_and_run_event_command,
        )
        if _confine_ok is not True:
            raise ImportError("specify_cli.events lacks script path confinement")
        sys.exit(
            resolve_and_run_event_command(
                command_name, _event_name, payload, project_root, timeout=timeout, envelope=envelope, native_event=native_event
            )
        )
    except (ImportError, TypeError):
        pass

    # Fallback: self-contained stdlib resolver (one-time/temporary installs).
    sys.exit(_run_inline(command_name, payload, project_root, timeout, envelope, native_event))


if __name__ == "__main__":
    main()
